#define MOTOR_PIN 2
#define MOTOR_DEFAULT_ESTADO false
#define MOTOR_DURACION_MS 10000

#define VENTANAS_DEFAULT_ESTADO false
#define VENTANAS_MODO_AUTOMATICO false

#define TEMP_SENSOR_PIN 15
#define TEMP_ALTA 30.0
#define TEMP_BAJA 20.0
#define TEMP_SENSOR_DELAY 2000

#define BOT_INTERVALO_NOTIFICACION 300000 // 5min
#define BOT_INTERVALO_CHEQUEO_MENSAJES 5000 // 5seg

#define LOOP_DELAY 100