version: "2"
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    ports:
      - "1883:1883"
    environment:
      - TZ=America/Argentina/Buenos_Aires

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"

  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
      - ./nodered/config/flows.json:/data/flows.json
      - ./nodered/config/package.json:/data/package.json
      - /dev/snd:/dev/snd
    links:
      - mqtt
      - influxdb
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/data:/var/lib/grafana

  telegraf:
    image: telegraf:1.16
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
