apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    uid: deojv7uc12d4we
    url: http://influxdb:8086
    database: iot2025_tp_final
    isDefault: true
    version: 1
    editable: true
